version: '3'
services:
 db:
  image: mongo
  networks:
      - todo-network

 adminmongo:
  image: mrvautin/adminmongo
  links:
    - db
  networks:
    - todo-network

 auth:
  build: ./auth
  links:
   - db
  depends_on:
   - db
  networks:
      - todo-network

 api:
  build: ./api
  links:
   - db
  depends_on:
   - db
  networks:
      - todo-network

networks:
  todo-network:
    driver: bridge