version: '3'
services:
 db:
  image: mongo
  ports:
   - "27017:27017"
  restart: always
 api:
  build: ./api
  volumes:
   - ./api/:/api
  ports:
   - "3000:3000"
  links:
   - db
  command: nodemon /api/server.js
 web:
  image: nginx:latest
  volumes:
   - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
   - "./etc/ssl:/etc/ssl"
   - "./web:/var/www/html"
   - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
  environment:
   - NGINX_HOST=${NGINX_HOST}
  ports:
   - "3200:80"
   - "3111:443"
  links:
   - api
  command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  restart: always
