version: '3'
services:
 db:
  image: mongo
  ports:
   - "27017:27017"
  restart: always
 api:
  build: ./api
  volumes:
   - ./api/:/api
  ports:
   - "3000:3000"
  links:
   - db
  command: nodemon /api/server.js
 web:
  image: 'todo-app'
  build: '.'
  ports:
   - 3200:80
